import hashlib

from typing import List

from wazuh_testing.constants.paths.configurations import BASE_CONF_PATH
from wazuh_testing.utils import file


def create_encryption_key(id: str, name: str, key: str) -> bytes:
    """Generate an encryption key using agent metadata and a key.

    The encryption key is generated by combining the MD5 hashes of the agent name,
    agent ID, and the provided key.

    Args:
        id (str): The ID of the agent.
        name (str): The name of the agent.
        key (str): The encryption key.

    Returns:
        bytes: The generated encryption key as bytes.
    """
    first_hash = (hashlib.md5(hashlib.md5(name.encode()).hexdigest().encode() +
                              hashlib.md5(id.encode()).hexdigest().encode()
                              ).hexdigest().encode())[:15]
    second_hash = hashlib.md5(key.encode()).hexdigest().encode()

    return second_hash + first_hash


def get_client_keys(path: str = f'{BASE_CONF_PATH}/client.keys') -> List[dict]:
    """Get client keys from a file.

    Args:
        path (str, optional): Path to the file containing the client keys.
            Defaults to f'{BASE_CONF_PATH}/client.keys'.

    Returns:
        List[dict]: A list of dictionaries representing the client keys.
            Each dictionary contains the following keys: 'id', 'name', 'ip', and 'key'.
    """
    if not file.exists_and_is_file(path):
        return [{'id': 100, 'name': 'ubuntu-agent', 'ip': 'any', 'key': 'TopSecret'}]

    keys = []
    for line in file.read_file_lines(path):
        (id, name, ip, key) = line.replace('\n', '').split(' ')
        keys.append({'id': id, 'name': name, 'ip': ip, 'key': key})

    return keys


def save_client_keys(keys: dict, path: str = f'{BASE_CONF_PATH}/client.keys') -> None:
    """
    Saves client keys to a specified path.

    Args:
        keys (dict): A dictionary containing the client keys.
            The dictionary must have the following keys: 'id', 'name', 'ip', and 'key'.
        path (str, optional): The path where the client keys will be saved.
            Defaults to '{BASE_CONF_PATH}/client.keys'.

    Raises:
        ValueError: If the value passed for `keys` is not a dictionary.
        ValueError: If the `keys` dictionary is invalid and does not contain the required keys.
    """
    if not isinstance(keys, dict):
        raise ValueError('The value `keys` must be a dict.')

    if not (keys.get('id') and keys.get('name') and keys.get('ip') and keys.get('key')):
        raise ValueError(
            'Invalid `keys` dict, must have keys `id`, `name`, `ip` and `key`.')

    file.write_file(path, keys)
